

title: R For Econometrics By Example 
author: Ahmed H. Darwish
logo: Econometrics By Example R Solutions Ahmed H. Darwish
copyright: 2024


execute:
  execute_notebooks: "off"


latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib


repository:
  url: https://github.com/42Ahmed/ecobyexampleR  
  path_to_book: docs  
  branch: master  

html:
  use_issues_button: true
  use_repository_button: true

include_toc: true

launch_buttons:
  colab_url: